apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rancher-demo
  template:
    metadata:
      labels:
        app: rancher-demo
    spec:
      containers:
        - name: rancher-demo
          image: monachus/rancher-demo:latest
          ports:
            - containerPort: 8080
          env:
            - name: TITLE
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: TITLE
            - name: COW_COLOR
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: COW_COLOR
