apiVersion: v1
kind: Service
metadata:
  name: rancher-demo-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: rancher-demo
  ports:
    - port: 80          # Port on the Service
      targetPort: 8080   # Port on the container
      nodePort: 30080    # Port on the Node (must be between 30000-32767)
